#!/bin/zsh

# Update Homebrew
brew update && brew upgrade && brew cleanup

# Update Mac Apple Store apps
#mas signin sethlabadie@icloud.com 'ARgoREco@432!@' # Doesn't work on never versions of Mac
# If you experience issues signing in this way, you can ask to sign in using a graphical dialog (provided by Mac App Store application):
# mas signin --dialog sethlabadie@icloud.com 'ARgoREco@432!@'
mas outdated
mas upgrade

softwareupdate --list
softwareupdate --download
sudo softwareupdate --install --all

pipx upgrade-all
pipx upgrade poetry
pyenv update

pyenv rehash # Updates pyenv shims to include recently downloaded Python versions

# dump .zcompdump, which is autogenerated, and which slows down zsh startup
rm ~/.config/.zsh/.zcompdump

# Occasionally run to remove .DS_Store files from home folder (it conflicts with GNU Stow)
sudo find / -name ".DS_Store" -depth -exec rm {} \;